<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="MoSaRTBackEnd_AnalysisRepository"
    nsURI="http://www.ensma.fr/MoSaRTBackEnd/AnalysisRepository"
    nsPrefix="MoSaRTBackEnd_AnalysisRepository">
  <eAnnotations
      source="http://www.eclipse.org/emf/2002/Ecore">
    <details
        key="invocationDelegates"
        value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details
        key="settingDelegates"
        value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details
        key="validationDelegates"
        value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="AnalysisRepository">
    <eOperations
        name="appropriateModelsFinder"
        upperBound="-1"
        eType="#//ContextModel">
      <eParameters
          name="resultSummary">
        <eGenericType
            eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments
              eClassifier="#//IdentificationRule"/>
          <eTypeArguments
              eClassifier="#//EvaluationResultType"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations
        name="identificationRuleChecker">
      <eGenericType
          eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments
            eClassifier="#//IdentificationRule"/>
        <eTypeArguments
            eClassifier="#//EvaluationResultType"/>
      </eGenericType>
      <eParameters
          name="root"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="allGeneralizationRelationships"
        upperBound="-1"
        eType="#//GeneralizationRelationship"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="allContextModels"
        upperBound="-1"
        eType="#//ContextModel"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="allRules"
        upperBound="-1"
        eType="#//IdentificationRule"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="allTests"
        upperBound="-1"
        eType="#//Test"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="allTools"
        upperBound="-1"
        eType="#//Tool"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="allTestFamilies"
        upperBound="-1"
        eType="#//TestFamily"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="mosartMetamodel"
        lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ContextModel">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="references"
        upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="trueValueRules"
        upperBound="-1"
        eType="#//IdentificationRule"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="falseValueRules"
        upperBound="-1"
        eType="#//IdentificationRule"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="undefinedValueRules"
        upperBound="-1"
        eType="#//IdentificationRule"
        derived="true">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details
            key="derivation"
            value="RuleToBeChecked.allInstances()->asOrderedSet()->excludesAll(self.trueValueRules->union(self.falseValueRules))"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="analysisTests"
        upperBound="-1"
        eType="#//Test"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Test">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="id"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="references"
        upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="itsTestFamily"
        eType="#//TestFamily"
        eOpposite="#//TestFamily/containedTests"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="toolsToApply"
        upperBound="-1"
        eType="#//Tool"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="characteristics"
        upperBound="-1"
        eType="#//TestCharacteristicType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="IdentificationRule">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="id"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="timingKind"
        lowerBound="1"
        eType="#//TimingKindType"
        defaultValueLiteral=""/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="componentKind"
        eType="#//ComponentKindType"
        defaultValueLiteral=""/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="rule"
        lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStringToStringMapEntry"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="ruleContext"
        lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Tool">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="id"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="mosartToToolPath"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="toolToMosartPath"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="TestFamily">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="references"
        upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="containedTests"
        upperBound="-1"
        eType="#//Test"
        eOpposite="#//Test/itsTestFamily"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="GeneralizationRelationship">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="specificModel"
        lowerBound="1"
        eType="#//ContextModel"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="genericModel"
        lowerBound="1"
        eType="#//ContextModel"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="behaviorKind"
        upperBound="-1"
        eType="#//BehaviorKindType"
        defaultValueLiteral=""/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="genericToSpecificPath"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="specificToGenericPath"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EEnum"
      name="TimingKindType">
    <eLiterals
        name="improving"
        value="2"/>
    <eLiterals
        name="worsening"
        value="1"
        literal="worsening"/>
    <eLiterals
        name="indifferent"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EEnum"
      name="ComponentKindType">
    <eLiterals
        name="hardware"/>
    <eLiterals
        name="software"
        value="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EEnum"
      name="BehaviorKindType">
    <eLiterals
        name="worstCaseBehavior"/>
    <eLiterals
        name="bestCaseBehavior"
        value="1"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EEnum"
      name="EvaluationResultType">
    <eLiterals
        name="True"
        value="1"/>
    <eLiterals
        name="False"
        value="2"/>
    <eLiterals
        name="Undefined"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="TestCharacteristicType"
      abstract="true"
      interface="true">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="testValue"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="comment"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="contexts"
        upperBound="-1"
        eType="#//ContextModel"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SustainabilityType"
      abstract="true"
      interface="true"
      eSuperTypes="#//TestCharacteristicType"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Deadline_Sustainability"
      eSuperTypes="#//SustainabilityType"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Jitter_Sustainability"
      eSuperTypes="#//SustainabilityType"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Period_Sustainability"
      eSuperTypes="#//SustainabilityType"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ExecutionTime_Sustainability"
      eSuperTypes="#//SustainabilityType"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="FeasibilityType"
      abstract="true"
      interface="true"
      eSuperTypes="#//TestCharacteristicType"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SufficientCondition"
      eSuperTypes="#//FeasibilityType"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="NecessaryCondition"
      eSuperTypes="#//FeasibilityType"/>
</ecore:EPackage>
